CREATE TABLE "account_sessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "account_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"account_id" integer NOT NULL,
	"encrypted_cookies" text NOT NULL,
	"encrypted_local_storage" text,
	"device_fingerprint" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"session_hash" varchar(64) NOT NULL,
	"is_valid" boolean DEFAULT true NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "automation_jobs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "automation_jobs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type" varchar(50) NOT NULL,
	"account_id" integer NOT NULL,
	"payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"status" varchar(20) DEFAULT 'queued' NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"max_attempts" integer DEFAULT 3 NOT NULL,
	"scheduled_at" timestamp NOT NULL,
	"started_at" timestamp,
	"completed_at" timestamp,
	"error" text,
	"error_details" jsonb,
	"worker_id" varchar(100),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "campaign_executions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "campaign_executions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"campaign_id" integer NOT NULL,
	"account_id" integer NOT NULL,
	"target_profile_url" varchar(500) NOT NULL,
	"target_name" varchar(255),
	"message" text NOT NULL,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"error" text,
	"scheduled_at" timestamp NOT NULL,
	"sent_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "campaigns" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "campaigns_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"scheduled_at" timestamp,
	"lead_file_id" integer NOT NULL,
	"profile_url_column" varchar(255) NOT NULL,
	"message_column" varchar(255),
	"message_template" text,
	"max_messages_per_day" integer DEFAULT 100 NOT NULL,
	"delay_between_messages" integer DEFAULT 30 NOT NULL,
	"account_rotation" boolean DEFAULT true NOT NULL,
	"messages_sent" integer DEFAULT 0 NOT NULL,
	"messages_failed" integer DEFAULT 0 NOT NULL,
	"messages_pending" integer DEFAULT 0 NOT NULL,
	"targets" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "instagram_accounts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "instagram_accounts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	"twofa" varchar(255),
	"status" varchar(50) DEFAULT 'warmup' NOT NULL,
	"health_score" integer DEFAULT 0 NOT NULL,
	"account_age" integer DEFAULT 0 NOT NULL,
	"followers_count" integer DEFAULT 0 NOT NULL,
	"following_count" integer DEFAULT 0 NOT NULL,
	"posts_count" integer DEFAULT 0 NOT NULL,
	"warmup_start_date" timestamp DEFAULT now(),
	"warmup_end_date" timestamp,
	"warmup_progress" integer DEFAULT 0 NOT NULL,
	"warmup_last_run" timestamp,
	"warmup_status" varchar(50) DEFAULT 'warming_up' NOT NULL,
	"daily_actions" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"daily_message_limit" integer DEFAULT 30 NOT NULL,
	"daily_message_count" integer DEFAULT 0 NOT NULL,
	"last_message_date" timestamp,
	"last_used" timestamp,
	"last_login_date" timestamp,
	"last_activity_date" timestamp,
	"restrictions" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"assigned_proxy_id" integer,
	"last_login_ip" varchar(45),
	"last_heartbeat" timestamp,
	"session_expires_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "instagram_accounts_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "lead_files" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lead_files_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"original_name" varchar(255) NOT NULL,
	"column_names" text[] NOT NULL,
	"selected_columns" text[] NOT NULL,
	"row_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "leads" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "leads_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"lead_file_id" integer NOT NULL,
	"profile_url" varchar(500) NOT NULL,
	"name" varchar(255),
	"custom_fields" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "message_templates" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "message_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"content" text NOT NULL,
	"variables" text[] DEFAULT '{}' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "proxies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "proxies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"provider" varchar(100) NOT NULL,
	"type" varchar(20) NOT NULL,
	"host" varchar(255) NOT NULL,
	"port" integer NOT NULL,
	"username" varchar(255),
	"password" varchar(255),
	"country" varchar(10) NOT NULL,
	"city" varchar(100),
	"isp" varchar(255),
	"status" varchar(20) DEFAULT 'available' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"success_rate" numeric(5, 4) DEFAULT '0.0000' NOT NULL,
	"response_time" integer DEFAULT 0 NOT NULL,
	"bandwidth_used" integer DEFAULT 0 NOT NULL,
	"monthly_limit" integer DEFAULT 0 NOT NULL,
	"assigned_to_account_id" integer,
	"sticky_expires_at" timestamp,
	"last_used" timestamp,
	"last_health_check" timestamp,
	"cost_per_month" numeric(10, 2) DEFAULT '0.00' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "system_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "system_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"level" varchar(20) NOT NULL,
	"category" varchar(50) NOT NULL,
	"message" text NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"account_id" integer,
	"proxy_id" integer,
	"job_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "warmup_activities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "warmup_activities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"account_id" integer NOT NULL,
	"action_type" varchar(50) NOT NULL,
	"target_profile" varchar(255),
	"success" boolean DEFAULT true NOT NULL,
	"error" text,
	"proxy_used" varchar(255),
	"response_time" integer,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "account_sessions" ADD CONSTRAINT "account_sessions_account_id_instagram_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."instagram_accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "automation_jobs" ADD CONSTRAINT "automation_jobs_account_id_instagram_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."instagram_accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_executions" ADD CONSTRAINT "campaign_executions_campaign_id_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaigns"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_executions" ADD CONSTRAINT "campaign_executions_account_id_instagram_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."instagram_accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaigns" ADD CONSTRAINT "campaigns_lead_file_id_lead_files_id_fk" FOREIGN KEY ("lead_file_id") REFERENCES "public"."lead_files"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "leads" ADD CONSTRAINT "leads_lead_file_id_lead_files_id_fk" FOREIGN KEY ("lead_file_id") REFERENCES "public"."lead_files"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "system_logs" ADD CONSTRAINT "system_logs_account_id_instagram_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."instagram_accounts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "system_logs" ADD CONSTRAINT "system_logs_proxy_id_proxies_id_fk" FOREIGN KEY ("proxy_id") REFERENCES "public"."proxies"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "system_logs" ADD CONSTRAINT "system_logs_job_id_automation_jobs_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."automation_jobs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "warmup_activities" ADD CONSTRAINT "warmup_activities_account_id_instagram_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."instagram_accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_sessions_account_idx" ON "account_sessions" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "account_sessions_hash_idx" ON "account_sessions" USING btree ("session_hash");--> statement-breakpoint
CREATE INDEX "account_sessions_valid_idx" ON "account_sessions" USING btree ("is_valid");--> statement-breakpoint
CREATE INDEX "automation_jobs_type_idx" ON "automation_jobs" USING btree ("type");--> statement-breakpoint
CREATE INDEX "automation_jobs_status_idx" ON "automation_jobs" USING btree ("status");--> statement-breakpoint
CREATE INDEX "automation_jobs_account_idx" ON "automation_jobs" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "automation_jobs_scheduled_idx" ON "automation_jobs" USING btree ("scheduled_at");--> statement-breakpoint
CREATE INDEX "automation_jobs_priority_idx" ON "automation_jobs" USING btree ("priority");--> statement-breakpoint
CREATE INDEX "instagram_accounts_status_idx" ON "instagram_accounts" USING btree ("status");--> statement-breakpoint
CREATE INDEX "instagram_accounts_health_score_idx" ON "instagram_accounts" USING btree ("health_score");--> statement-breakpoint
CREATE INDEX "instagram_accounts_proxy_idx" ON "instagram_accounts" USING btree ("assigned_proxy_id");--> statement-breakpoint
CREATE INDEX "proxies_status_idx" ON "proxies" USING btree ("status");--> statement-breakpoint
CREATE INDEX "proxies_country_idx" ON "proxies" USING btree ("country");--> statement-breakpoint
CREATE INDEX "proxies_type_idx" ON "proxies" USING btree ("type");--> statement-breakpoint
CREATE INDEX "proxies_assigned_idx" ON "proxies" USING btree ("assigned_to_account_id");--> statement-breakpoint
CREATE INDEX "system_logs_level_idx" ON "system_logs" USING btree ("level");--> statement-breakpoint
CREATE INDEX "system_logs_category_idx" ON "system_logs" USING btree ("category");--> statement-breakpoint
CREATE INDEX "system_logs_account_idx" ON "system_logs" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "system_logs_created_idx" ON "system_logs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "warmup_activities_account_idx" ON "warmup_activities" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "warmup_activities_type_idx" ON "warmup_activities" USING btree ("action_type");--> statement-breakpoint
CREATE INDEX "warmup_activities_created_idx" ON "warmup_activities" USING btree ("created_at");